---
title: "preprocessinh"
output: html_document
date: "2025-01-17"
---

```{r}
library(dplyr)
library(tidyr)
vc <- function(col_df){
  table(col_df, useNA = 'ifany')
}
```


```{r}
vc(raw$Drugs)
vc(raw$Genes)

```


```{r}
filtered1 <- raw %>% select(PharmGKB.ID, Variant, Drugs, Association, Genes)
filtered1
```

```{r}
# Split the 'Variant' column by "; " to extract individual CYP types
split_variants <- strsplit(filtered1$Variant, ";\\s*")

# Get unique CYP types
unique_cyps <- sort(unique(unlist(split_variants)))

# Create a new data frame with 'PharmGKB.ID' as row names and CYP types as columns
result_df <- data.frame(matrix(0, nrow = nrow(filtered1), ncol = length(unique_cyps)))
rownames(result_df) <- filtered1$PharmGKB.ID
colnames(result_df) <- unique_cyps

# Populate the new data frame
for (i in seq_along(split_variants)) {
  result_df[i, unlist(split_variants[i])] <- 1
}

# View the resulting data frame
head(result_df)


```


